package DAO.Entity;
// Generated 26.08.2016 15:13:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ClientService generated by hbm2java
 */
@Entity
@Table(name="CLIENT_SERVICE"
)
public class ClientService  implements java.io.Serializable {


     private int id;
     private Client client;
     private Service service;
     private Set<Consumption> consumptions = new HashSet<Consumption>(0);

    public ClientService() {
    }

	
    public ClientService(int id, Client client, Service service) {
        this.id = id;
        this.client = client;
        this.service = service;
    }
    public ClientService(int id, Client client, Service service, Set<Consumption> consumptions) {
       this.id = id;
       this.client = client;
       this.service = service;
       this.consumptions = consumptions;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENT", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_SERVICE", nullable=false)
    public Service getService() {
        return this.service;
    }
    
    public void setService(Service service) {
        this.service = service;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="clientService")
    public Set<Consumption> getConsumptions() {
        return this.consumptions;
    }
    
    public void setConsumptions(Set<Consumption> consumptions) {
        this.consumptions = consumptions;
    }




}


