package DAO.Entity;
// Generated 26.08.2016 15:13:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="CLIENT"
    , uniqueConstraints = @UniqueConstraint(columnNames="CLIENT_NAME") 
)
public class Client  implements java.io.Serializable {


     private int id;
     private String clientName;
     private Set<BillClient> billClients = new HashSet<BillClient>(0);
     private Set<ClientService> clientServices = new HashSet<ClientService>(0);

    public Client() {
    }

	
    public Client(int id, String clientName) {
        this.id = id;
        this.clientName = clientName;
    }
    public Client(int id, String clientName, Set<BillClient> billClients, Set<ClientService> clientServices) {
       this.id = id;
       this.clientName = clientName;
       this.billClients = billClients;
       this.clientServices = clientServices;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="CLIENT_NAME", unique=true, nullable=false, length=25)
    public String getClientName() {
        return this.clientName;
    }
    
    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<BillClient> getBillClients() {
        return this.billClients;
    }
    
    public void setBillClients(Set<BillClient> billClients) {
        this.billClients = billClients;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<ClientService> getClientServices() {
        return this.clientServices;
    }
    
    public void setClientServices(Set<ClientService> clientServices) {
        this.clientServices = clientServices;
    }




}


