package DAO.Entity;
// Generated 26.08.2016 15:13:22 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Consumption generated by hbm2java
 */
@Entity
@Table(name="CONSUMPTION"
)
public class Consumption  implements java.io.Serializable {


     private int id;
     private ClientService clientService;
     private int valuesConsumption;

    public Consumption() {
    }

    public Consumption(int id, ClientService clientService, int valuesConsumption) {
       this.id = id;
       this.clientService = clientService;
       this.valuesConsumption = valuesConsumption;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_CLIENT_SERVICE", nullable=false)
    public ClientService getClientService() {
        return this.clientService;
    }
    
    public void setClientService(ClientService clientService) {
        this.clientService = clientService;
    }

    
    @Column(name="VALUES_CONSUMPTION", nullable=false)
    public int getValuesConsumption() {
        return this.valuesConsumption;
    }
    
    public void setValuesConsumption(int valuesConsumption) {
        this.valuesConsumption = valuesConsumption;
    }




}


