package DAO.Entity;
// Generated 26.08.2016 15:13:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name="SERVICE"
    , uniqueConstraints = @UniqueConstraint(columnNames="SERVICE_NAME") 
)
public class Service  implements java.io.Serializable {


     private int id;
     private String serviceName;
     private String operation;
     private double parametr;
     private Set<ClientService> clientServices = new HashSet<ClientService>(0);

    public Service() {
    }

	
    public Service(int id, String serviceName, String operation, double parametr) {
        this.id = id;
        this.serviceName = serviceName;
        this.operation = operation;
        this.parametr = parametr;
    }
    public Service(int id, String serviceName, String operation, double parametr, Set<ClientService> clientServices) {
       this.id = id;
       this.serviceName = serviceName;
       this.operation = operation;
       this.parametr = parametr;
       this.clientServices = clientServices;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="SERVICE_NAME", unique=true, nullable=false, length=25)
    public String getServiceName() {
        return this.serviceName;
    }
    
    public void setServiceName(String serviceName) {
        this.serviceName = serviceName;
    }

    
    @Column(name="OPERATION", nullable=false, length=10)
    public String getOperation() {
        return this.operation;
    }
    
    public void setOperation(String operation) {
        this.operation = operation;
    }

    
    @Column(name="PARAMETR", nullable=false, precision=7, scale=0)
    public double getParametr() {
        return this.parametr;
    }
    
    public void setParametr(double parametr) {
        this.parametr = parametr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="service")
    public Set<ClientService> getClientServices() {
        return this.clientServices;
    }
    
    public void setClientServices(Set<ClientService> clientServices) {
        this.clientServices = clientServices;
    }




}


